Repository radicle-dev/radicle-interface, pull requests merged in 2022-09, with the labels that each got.

#358 Show loading indicators after a delay
  src/Loading.svelte
Labels: ux

#357 Convert colon-delimited string emojis to unicode emojis
  package.json
  src/Form.svelte
  src/Markdown.svelte
  src/Options.svelte
  src/emojis.ts
  src/utils.test.ts
  src/utils.ts
Labels: bug

#298 Add theme switching button
  index.html
  public/colors.css
  public/elevations.css
  public/index.css
  public/typography.css
  src/Address.svelte
  src/App.svelte
  src/Authorship.svelte
  src/Avatar.svelte
  src/Badge.svelte
  src/BlockTimer.svelte
  src/Button.svelte
  src/Clipboard.svelte
  src/ColorPalette.svelte
  src/Comment.svelte
  src/Dropdown.svelte
  src/Header.svelte
  src/Icon.svelte
  src/Input.svelte
  src/Loading.svelte
  src/Markdown.svelte
  src/Message.svelte
  src/MobileNavbar.svelte
  src/Modal.svelte
  src/Placeholder.svelte
  src/RadicleUrn.svelte
  src/ReactionSelector.svelte
  src/SeedAddress.svelte
  src/ThemeToggle.svelte
  src/ToggleButton.svelte
  src/base/home/Index.svelte
  src/base/projects/Blob.svelte
  src/base/projects/BranchSelector.svelte
  src/base/projects/Browser.svelte
  src/base/projects/CloneButton.svelte
  src/base/projects/Commit.svelte
  src/base/projects/Commit/CommitAuthorship.svelte
  src/base/projects/Commit/CommitTeaser.svelte
  src/base/projects/Commit/CommitVerifiedBadge.svelte
  src/base/projects/Header.svelte
  src/base/projects/History.svelte
  src/base/projects/Issue.svelte
  src/base/projects/Issue/IssueTeaser.svelte
  src/base/projects/Patch.svelte
  src/base/projects/Patch/PatchSideBar.svelte
  src/base/projects/Patch/PatchTabBar.svelte
  src/base/projects/Patch/PatchTeaser.svelte
  src/base/projects/PeerSelector.svelte
  src/base/projects/ProjectMeta.svelte
  src/base/projects/Readme.svelte
  src/base/projects/SourceBrowser/FileDiff.svelte
  src/base/projects/Tree/File.svelte
  src/base/projects/Tree/Folder.svelte
  src/base/projects/Widget.svelte
  src/base/seeds/View.svelte
  src/project.ts
Labels: ux

#388 Use Metamask as provider before trying to use Alchemy
  src/config.ts
Labels: enhancement

#407 Gracefully handle API quota exhaustion
  src/base/orgs/Org.ts
  src/utils.ts
Labels: bug

#409 Move `seeds.pinned` out of network scope
  src/config.json
  src/config.ts
Labels: bug

#408 Stop `TextInput` `keydown` event propagation
  src/TextInput.svelte
Labels: bug

#410 Fix `isSafe` util function
  src/utils.ts
Labels: bug

#416 Lowercase ENS name search query
  src/resolver.ts
Labels: ux

#414 Fix project nav buttons height
  src/base/projects/BranchSelector.svelte
  src/base/projects/CloneButton.svelte
  src/base/projects/Header.svelte
  src/base/projects/PeerSelector.svelte
Labels: design

#411 Show delegate badge in commits
  cypress/e2e/projectCommits.spec.ts
  src/base/projects/Commit/CommitAuthorship.svelte
  src/base/projects/Commit/CommitTeaser.svelte
  src/base/projects/Commit/CommitVerifiedBadge.svelte
Labels: enhancement

#418 Add shake animation to search component when no results
  src/Header.svelte
  src/Search.svelte
  src/base/home/Index.svelte
  src/components/Modal/SearchResults.svelte
  src/project.ts
  src/resolver.ts
Labels: ux
