Repository radicle-dev/radicle-interface, pull requests merged in 2022-08, with the labels that each got.

#292 Improve error message when missing web3 provider
  src/config.ts
Labels: enhancement

#295 Hide anchored widget behind a feature flag
  cypress/e2e/project.spec.ts
  src/base/projects/Header.svelte
  src/base/projects/Project.svelte
Labels: ux

#293 Add placeholder for empty issue state
  src/base/projects/Issue/IssueFilter.svelte
Labels: ux

#304 Fix spurious requests
  cypress/fixtures/projectInfo.json
  src/base/projects/Header.svelte
  src/project.ts
Labels: bug

#316 Improve handling of low commit counts in repo activity
  src/Diagram.svelte
Labels: enhancement

#310 feat: add name length check at registration
  src/base/registrations/Index.svelte
Labels: enhancement

#320 Change Node version to v16
  .nvmrc
  .tool-versions
Labels: bug

#317 Always use the same timezone when running unit tests
  package.json
Labels: bug

#308 Remove WalletConnect compatible link
  src/components/Modal/ConnectWallet.svelte
Labels: bug

#305 Improve Profile Edit and Transfer buttons
  src/base/registrations/View.svelte
Labels: ux

#326 Use ethers defaultProvider when in development mode
  src/config.ts
Labels: ux

#339 Skip absolute image URLs for getImage in Markdown.svelte
  src/Markdown.svelte
Labels: bug

#331 Add tooltips for Dropdowns
  src/Dropdown.svelte
  src/SeedDropdown.svelte
  src/base/projects/BranchSelector.svelte
  src/base/projects/Patch/PatchTabBar.svelte
  src/base/projects/PeerSelector.svelte
Labels: ux

#332 Add small explainer to the name registration form
  src/base/registrations/Index.svelte
Labels: ux

#330 Implements activity endpoint for project graph
  src/Diagram.svelte
  src/base/projects/Widget.svelte
  src/commit.ts
  src/project.ts
Labels: enhancement

#333 Improve UX on issue and patches stats in project header
  src/base/projects/Header.svelte
  src/project.ts
Labels: ux
